import { Inter } from "next/font/google";
import ReduxProvider from "../../lib/provider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Beauty Check",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ margin: 0, padding: 0, backgroundColor: "#1b1b2a" }}
      >
        <div id="portal"></div>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
